[project]
name = "bettiloss"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gudhi>=3.12.0",
    "jupyter-bokeh>=4.0.5",
    "matplotlib>=3.10.9",
    "monai>=1.5.2",
    "pandas>=3.0.2",
    "panel>=1.8.10",
    "safetensors>=0.7.0",
    "scikit-image>=0.26.0",
]

[dependency-groups]
cpu = [
    "torch>=2.11.0",
    "torchvision>=0.26.0",
]
cuda = [
    "torch>=2.11.0",
    "torchvision>=0.26.0",
]

[tool.uv]
default-groups = ["cpu"]
conflicts = [
    [
        { group = "cpu" },
        { group = "cuda" },
    ],
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", group = "cpu" },
    { index = "pytorch-cu128", group = "cuda" },
]
torchvision = [
    { index = "pytorch-cpu", group = "cpu" },
    { index = "pytorch-cu128", group = "cuda" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
